object StatusForm: TStatusForm
  Left = 200
  Top = 200
  BorderIcons = [biSystemMenu, biMinimize]
  Caption = 'EDA Agent MCP'
  ClientHeight = 813
  ClientWidth = 475
  Color = 1710878
  Constraints.MinHeight = 625
  Constraints.MinWidth = 450
  Font.Charset = DEFAULT_CHARSET
  Font.Color = 14803686
  Font.Height = -14
  Font.Name = 'Segoe UI'
  Font.Style = []
  FormStyle = fsStayOnTop
  OldCreateOrder = False
  Position = poDesigned
  OnClose = StatusFormClose
  PixelsPerInch = 120
  TextHeight = 19
  object pnl_Header: TPanel
    Left = 0
    Top = 0
    Width = 475
    Height = 60
    Margins.Left = 4
    Margins.Top = 4
    Margins.Right = 4
    Margins.Bottom = 4
    Align = alTop
    BevelOuter = bvNone
    Color = 2105638
    ParentBackground = False
    TabOrder = 2
    object lbl_Spinner: TLabel
      Left = 35
      Top = 18
      Width = 18
      Height = 22
      Margins.Left = 4
      Margins.Top = 4
      Margins.Right = 4
      Margins.Bottom = 4
      Alignment = taCenter
      AutoSize = False
      Font.Charset = DEFAULT_CHARSET
      Font.Color = 16752202
      Font.Height = -18
      Font.Name = 'Segoe UI'
      Font.Style = []
      ParentFont = False
    end
    object lbl_Status: TLabel
      Left = 58
      Top = 18
      Width = 305
      Height = 25
      Margins.Left = 4
      Margins.Top = 4
      Margins.Right = 4
      Margins.Bottom = 4
      AutoSize = False
      Caption = 'idle'
      EllipsisPosition = epEndEllipsis
      Font.Charset = DEFAULT_CHARSET
      Font.Color = 14803686
      Font.Height = -16
      Font.Name = 'Segoe UI Semibold'
      Font.Style = []
      ParentFont = False
    end
    object lbl_Version: TLabel
      Left = 363
      Top = 23
      Width = 100
      Height = 17
      Margins.Left = 4
      Margins.Top = 4
      Margins.Right = 4
      Margins.Bottom = 4
      Alignment = taRightJustify
      AutoSize = False
      Caption = 'v?'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = 6909043
      Font.Height = -13
      Font.Name = 'Consolas'
      Font.Style = []
      ParentFont = False
    end
    object pnl_StatusDot: TPanel
      Left = 18
      Top = 24
      Width = 12
      Height = 12
      Margins.Left = 4
      Margins.Top = 4
      Margins.Right = 4
      Margins.Bottom = 4
      BevelOuter = bvNone
      Color = 6603883
      ParentBackground = False
      TabOrder = 0
    end
  end
  object pnl_KPIs: TPanel
    Left = 0
    Top = 60
    Width = 475
    Height = 95
    Margins.Left = 4
    Margins.Top = 4
    Margins.Right = 4
    Margins.Bottom = 4
    Align = alTop
    BevelOuter = bvNone
    Color = 1710878
    ParentBackground = False
    TabOrder = 3
    object pnl_K1: TPanel
      Left = 15
      Top = 8
      Width = 105
      Height = 80
      Margins.Left = 4
      Margins.Top = 4
      Margins.Right = 4
      Margins.Bottom = 4
      BevelOuter = bvNone
      Color = 2434603
      ParentBackground = False
      TabOrder = 0
      object lbl_LblUp: TLabel
        Left = 0
        Top = 10
        Width = 105
        Height = 15
        Margins.Left = 4
        Margins.Top = 4
        Margins.Right = 4
        Margins.Bottom = 4
        Alignment = taCenter
        AutoSize = False
        Caption = 'UPTIME'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = 9146006
        Font.Height = -11
        Font.Name = 'Segoe UI'
        Font.Style = [fsBold]
        ParentFont = False
      end
      object lbl_ValUp: TLabel
        Left = 0
        Top = 30
        Width = 105
        Height = 35
        Margins.Left = 4
        Margins.Top = 4
        Margins.Right = 4
        Margins.Bottom = 4
        Alignment = taCenter
        AutoSize = False
        Caption = '0s'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = 14803686
        Font.Height = -24
        Font.Name = 'Segoe UI Semibold'
        Font.Style = []
        ParentFont = False
      end
    end
    object pnl_K2: TPanel
      Left = 130
      Top = 8
      Width = 105
      Height = 80
      Margins.Left = 4
      Margins.Top = 4
      Margins.Right = 4
      Margins.Bottom = 4
      BevelOuter = bvNone
      Color = 2434603
      ParentBackground = False
      TabOrder = 1
      object lbl_LblReq: TLabel
        Left = 0
        Top = 10
        Width = 105
        Height = 15
        Margins.Left = 4
        Margins.Top = 4
        Margins.Right = 4
        Margins.Bottom = 4
        Alignment = taCenter
        AutoSize = False
        Caption = 'REQUESTS'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = 9146006
        Font.Height = -11
        Font.Name = 'Segoe UI'
        Font.Style = [fsBold]
        ParentFont = False
      end
      object lbl_ValReq: TLabel
        Left = 0
        Top = 30
        Width = 105
        Height = 35
        Margins.Left = 4
        Margins.Top = 4
        Margins.Right = 4
        Margins.Bottom = 4
        Alignment = taCenter
        AutoSize = False
        Caption = '0'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = 14803686
        Font.Height = -24
        Font.Name = 'Segoe UI Semibold'
        Font.Style = []
        ParentFont = False
      end
    end
    object pnl_K3: TPanel
      Left = 245
      Top = 8
      Width = 105
      Height = 80
      Margins.Left = 4
      Margins.Top = 4
      Margins.Right = 4
      Margins.Bottom = 4
      BevelOuter = bvNone
      Color = 2434603
      ParentBackground = False
      TabOrder = 2
      object lbl_LblMs: TLabel
        Left = 0
        Top = 10
        Width = 105
        Height = 15
        Margins.Left = 4
        Margins.Top = 4
        Margins.Right = 4
        Margins.Bottom = 4
        Alignment = taCenter
        AutoSize = False
        Caption = 'BUSY TIME'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = 9146006
        Font.Height = -11
        Font.Name = 'Segoe UI'
        Font.Style = [fsBold]
        ParentFont = False
      end
      object lbl_ValMs: TLabel
        Left = 0
        Top = 30
        Width = 105
        Height = 35
        Margins.Left = 4
        Margins.Top = 4
        Margins.Right = 4
        Margins.Bottom = 4
        Alignment = taCenter
        AutoSize = False
        Caption = '0s'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = 14803686
        Font.Height = -24
        Font.Name = 'Segoe UI Semibold'
        Font.Style = []
        ParentFont = False
      end
    end
    object pnl_K4: TPanel
      Left = 360
      Top = 8
      Width = 100
      Height = 80
      Margins.Left = 4
      Margins.Top = 4
      Margins.Right = 4
      Margins.Bottom = 4
      BevelOuter = bvNone
      Color = 2434603
      ParentBackground = False
      TabOrder = 3
      object lbl_LblStop: TLabel
        Left = 0
        Top = 10
        Width = 100
        Height = 15
        Margins.Left = 4
        Margins.Top = 4
        Margins.Right = 4
        Margins.Bottom = 4
        Alignment = taCenter
        AutoSize = False
        Caption = 'AUTO-OFF IN'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = 9146006
        Font.Height = -11
        Font.Name = 'Segoe UI'
        Font.Style = [fsBold]
        ParentFont = False
      end
      object lbl_ValStop: TLabel
        Left = 0
        Top = 30
        Width = 100
        Height = 35
        Margins.Left = 4
        Margins.Top = 4
        Margins.Right = 4
        Margins.Bottom = 4
        Alignment = taCenter
        AutoSize = False
        Caption = '10m'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = 6603883
        Font.Height = -24
        Font.Name = 'Segoe UI Semibold'
        Font.Style = []
        ParentFont = False
      end
    end
  end
  object pnl_ErrBar: TPanel
    Left = 0
    Top = 155
    Width = 475
    Height = 23
    Margins.Left = 4
    Margins.Top = 4
    Margins.Right = 4
    Margins.Bottom = 4
    Align = alTop
    BevelOuter = bvNone
    Color = 1710878
    ParentBackground = False
    TabOrder = 4
    object lbl_LastErr: TLabel
      Left = 18
      Top = 3
      Width = 442
      Height = 17
      Margins.Left = 4
      Margins.Top = 4
      Margins.Right = 4
      Margins.Bottom = 4
      AutoSize = False
      EllipsisPosition = epEndEllipsis
      Font.Charset = DEFAULT_CHARSET
      Font.Color = 7171071
      Font.Height = -13
      Font.Name = 'Consolas'
      Font.Style = []
      ParentFont = False
    end
  end
  object pnl_Primary: TPanel
    Left = 0
    Top = 178
    Width = 475
    Height = 50
    Margins.Left = 4
    Margins.Top = 4
    Margins.Right = 4
    Margins.Bottom = 4
    Align = alTop
    BevelOuter = bvNone
    Color = 1710878
    ParentBackground = False
    TabOrder = 5
    object btn_OpenWeb: TPanel
      Left = 15
      Top = 8
      Width = 445
      Height = 35
      Margins.Left = 4
      Margins.Top = 4
      Margins.Right = 4
      Margins.Bottom = 4
      BevelOuter = bvNone
      Caption = 'Open Dashboard  (waiting for MCP)'
      Color = 2434603
      Font.Charset = DEFAULT_CHARSET
      Font.Color = 6909043
      Font.Height = -15
      Font.Name = 'Segoe UI Semibold'
      Font.Style = []
      ParentBackground = False
      ParentFont = False
      TabOrder = 0
      OnClick = btn_OpenWebClick
      OnMouseEnter = btn_OpenWebEnter
      OnMouseLeave = btn_OpenWebLeave
    end
  end
  object pnl_Controls: TPanel
    Left = 0
    Top = 228
    Width = 475
    Height = 87
    Margins.Left = 4
    Margins.Top = 4
    Margins.Right = 4
    Margins.Bottom = 4
    Align = alTop
    BevelOuter = bvNone
    Color = 1710878
    ParentBackground = False
    TabOrder = 6
    object lbl_FilterLabel: TLabel
      Left = 18
      Top = 50
      Width = 30
      Height = 17
      Margins.Left = 4
      Margins.Top = 4
      Margins.Right = 4
      Margins.Bottom = 4
      Caption = 'filter'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = 9146006
      Font.Height = -13
      Font.Name = 'Segoe UI'
      Font.Style = [fsBold]
      ParentFont = False
    end
    object btn_Pause: TPanel
      Left = 15
      Top = 5
      Width = 100
      Height = 30
      Cursor = crHandPoint
      Margins.Left = 4
      Margins.Top = 4
      Margins.Right = 4
      Margins.Bottom = 4
      BevelOuter = bvNone
      Caption = 'Pause'
      Color = 2763826
      Font.Charset = DEFAULT_CHARSET
      Font.Color = 14803686
      Font.Height = -14
      Font.Name = 'Segoe UI'
      Font.Style = []
      ParentBackground = False
      ParentFont = False
      TabOrder = 0
      OnClick = btn_PauseClick
      OnMouseEnter = btn_PauseEnter
      OnMouseLeave = btn_PauseLeave
    end
    object btn_Renew: TPanel
      Left = 120
      Top = 5
      Width = 100
      Height = 30
      Cursor = crHandPoint
      Margins.Left = 4
      Margins.Top = 4
      Margins.Right = 4
      Margins.Bottom = 4
      BevelOuter = bvNone
      Caption = 'Renew'
      Color = 2763826
      Font.Charset = DEFAULT_CHARSET
      Font.Color = 14803686
      Font.Height = -14
      Font.Name = 'Segoe UI'
      Font.Style = []
      ParentBackground = False
      ParentFont = False
      TabOrder = 1
      OnClick = btn_RenewClick
      OnMouseEnter = btn_RenewEnter
      OnMouseLeave = btn_RenewLeave
    end
    object btn_ClearLog: TPanel
      Left = 225
      Top = 5
      Width = 100
      Height = 30
      Cursor = crHandPoint
      Margins.Left = 4
      Margins.Top = 4
      Margins.Right = 4
      Margins.Bottom = 4
      BevelOuter = bvNone
      Caption = 'Clear log'
      Color = 2763826
      Font.Charset = DEFAULT_CHARSET
      Font.Color = 14803686
      Font.Height = -14
      Font.Name = 'Segoe UI'
      Font.Style = []
      ParentBackground = False
      ParentFont = False
      TabOrder = 2
      OnClick = btn_ClearLogClick
      OnMouseEnter = btn_ClearLogEnter
      OnMouseLeave = btn_ClearLogLeave
    end
    object btn_Detach: TPanel
      Left = 360
      Top = 5
      Width = 100
      Height = 30
      Cursor = crHandPoint
      Margins.Left = 4
      Margins.Top = 4
      Margins.Right = 4
      Margins.Bottom = 4
      BevelOuter = bvNone
      Caption = 'Detach'
      Color = 11617605
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -14
      Font.Name = 'Segoe UI Semibold'
      Font.Style = []
      ParentBackground = False
      ParentFont = False
      TabOrder = 3
      OnClick = btn_DetachClick
      OnMouseEnter = btn_DetachEnter
      OnMouseLeave = btn_DetachLeave
    end
    object edt_Filter: TEdit
      Left = 60
      Top = 48
      Width = 135
      Height = 25
      Margins.Left = 4
      Margins.Top = 4
      Margins.Right = 4
      Margins.Bottom = 4
      BorderStyle = bsNone
      Color = 2434603
      Font.Charset = DEFAULT_CHARSET
      Font.Color = 14803686
      Font.Height = -14
      Font.Name = 'Consolas'
      Font.Style = []
      ParentFont = False
      TabOrder = 4
      OnChange = edt_FilterChange
    end
    object chk_HidePings: TPanel
      Left = 203
      Top = 50
      Width = 87
      Height = 23
      Cursor = crHandPoint
      Margins.Left = 4
      Margins.Top = 4
      Margins.Right = 4
      Margins.Bottom = 4
      Alignment = taLeftJustify
      BevelOuter = bvNone
      Caption = ' [x] pings'
      Color = 1710878
      Font.Charset = DEFAULT_CHARSET
      Font.Color = 13224913
      Font.Height = -14
      Font.Name = 'Segoe UI'
      Font.Style = []
      ParentBackground = False
      ParentFont = False
      TabOrder = 5
      OnClick = chk_HidePingsClick
      OnMouseEnter = chk_HidePingsEnter
      OnMouseLeave = chk_HidePingsLeave
    end
    object chk_OnlySlow: TPanel
      Left = 295
      Top = 50
      Width = 100
      Height = 23
      Cursor = crHandPoint
      Margins.Left = 4
      Margins.Top = 4
      Margins.Right = 4
      Margins.Bottom = 4
      Alignment = taLeftJustify
      BevelOuter = bvNone
      Caption = ' [ ] >100ms'
      Color = 1710878
      Font.Charset = DEFAULT_CHARSET
      Font.Color = 13224913
      Font.Height = -14
      Font.Name = 'Segoe UI'
      Font.Style = []
      ParentBackground = False
      ParentFont = False
      TabOrder = 6
      OnClick = chk_OnlySlowClick
      OnMouseEnter = chk_OnlySlowEnter
      OnMouseLeave = chk_OnlySlowLeave
    end
    object chk_OnTop: TPanel
      Left = 400
      Top = 50
      Width = 70
      Height = 23
      Cursor = crHandPoint
      Margins.Left = 4
      Margins.Top = 4
      Margins.Right = 4
      Margins.Bottom = 4
      Alignment = taLeftJustify
      BevelOuter = bvNone
      Caption = ' [x] pin'
      Color = 1710878
      Font.Charset = DEFAULT_CHARSET
      Font.Color = 13224913
      Font.Height = -14
      Font.Name = 'Segoe UI'
      Font.Style = []
      ParentBackground = False
      ParentFont = False
      TabOrder = 7
      OnClick = chk_OnTopClick
      OnMouseEnter = chk_OnTopEnter
      OnMouseLeave = chk_OnTopLeave
    end
  end
  object pnl_TabBar: TPanel
    Left = 0
    Top = 315
    Width = 475
    Height = 33
    Margins.Left = 4
    Margins.Top = 4
    Margins.Right = 4
    Margins.Bottom = 4
    Align = alTop
    BevelOuter = bvNone
    Color = 2105638
    ParentBackground = False
    TabOrder = 7
    object lbl_LogHint: TLabel
      Left = 175
      Top = 9
      Width = 285
      Height = 17
      Margins.Left = 4
      Margins.Top = 4
      Margins.Right = 4
      Margins.Bottom = 4
      Alignment = taRightJustify
      AutoSize = False
      Caption = 'newest at top'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = 6909043
      Font.Height = -13
      Font.Name = 'Segoe UI'
      Font.Style = []
      ParentFont = False
    end
    object tab_Log: TPanel
      Left = 15
      Top = 0
      Width = 80
      Height = 33
      Cursor = crHandPoint
      Margins.Left = 4
      Margins.Top = 4
      Margins.Right = 4
      Margins.Bottom = 4
      BevelOuter = bvNone
      Caption = 'Log'
      Color = 1710878
      Font.Charset = DEFAULT_CHARSET
      Font.Color = 16752202
      Font.Height = -14
      Font.Name = 'Segoe UI Semibold'
      Font.Style = []
      ParentBackground = False
      ParentFont = False
      TabOrder = 0
      OnClick = tab_LogClick
      OnMouseEnter = tab_LogEnter
      OnMouseLeave = tab_LogLeave
    end
    object tab_Perf: TPanel
      Left = 95
      Top = 0
      Width = 80
      Height = 33
      Cursor = crHandPoint
      Margins.Left = 4
      Margins.Top = 4
      Margins.Right = 4
      Margins.Bottom = 4
      BevelOuter = bvNone
      Caption = 'Perf'
      Color = 2105638
      Font.Charset = DEFAULT_CHARSET
      Font.Color = 9146006
      Font.Height = -14
      Font.Name = 'Segoe UI'
      Font.Style = []
      ParentBackground = False
      ParentFont = False
      TabOrder = 1
      OnClick = tab_PerfClick
      OnMouseEnter = tab_PerfEnter
      OnMouseLeave = tab_PerfLeave
    end
  end
  object mmo_Log: TMemo
    Left = 0
    Top = 348
    Width = 475
    Height = 427
    Margins.Left = 4
    Margins.Top = 4
    Margins.Right = 4
    Margins.Bottom = 4
    Align = alClient
    BorderStyle = bsNone
    Color = 1513499
    Font.Charset = DEFAULT_CHARSET
    Font.Color = 13948116
    Font.Height = -14
    Font.Name = 'Consolas'
    Font.Style = []
    ParentFont = False
    ReadOnly = True
    ScrollBars = ssVertical
    TabOrder = 0
  end
  object mmo_Perf: TMemo
    Left = 0
    Top = 348
    Width = 475
    Height = 427
    Margins.Left = 4
    Margins.Top = 4
    Margins.Right = 4
    Margins.Bottom = 4
    Align = alClient
    BorderStyle = bsNone
    Color = 1513499
    Font.Charset = DEFAULT_CHARSET
    Font.Color = 13948116
    Font.Height = -14
    Font.Name = 'Consolas'
    Font.Style = []
    ParentFont = False
    ReadOnly = True
    ScrollBars = ssVertical
    TabOrder = 1
    Visible = False
  end
  object pnl_Footer: TPanel
    Left = 0
    Top = 775
    Width = 475
    Height = 38
    Margins.Left = 4
    Margins.Top = 4
    Margins.Right = 4
    Margins.Bottom = 4
    Align = alBottom
    BevelOuter = bvNone
    Color = 1513499
    ParentBackground = False
    TabOrder = 8
    object lbl_FooterHint: TLabel
      Left = 15
      Top = 4
      Width = 445
      Height = 14
      Margins.Left = 4
      Margins.Top = 4
      Margins.Right = 4
      Margins.Bottom = 4
      AutoSize = False
      Caption = 'Run standalone (no AI needed):'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = 6909043
      Font.Height = -11
      Font.Name = 'Segoe UI'
      Font.Style = []
      ParentFont = False
    end
    object lbl_LaunchCmd: TLabel
      Left = 15
      Top = 18
      Width = 350
      Height = 16
      Margins.Left = 4
      Margins.Top = 4
      Margins.Right = 4
      Margins.Bottom = 4
      AutoSize = False
      Caption = 'python -m eda_agent.server dashboard --port 8766'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = 13948116
      Font.Height = -14
      Font.Name = 'Consolas'
      Font.Style = []
      ParentFont = False
    end
    object btn_CopyCmd: TPanel
      Left = 375
      Top = 8
      Width = 85
      Height = 25
      Cursor = crHandPoint
      Margins.Left = 4
      Margins.Top = 4
      Margins.Right = 4
      Margins.Bottom = 4
      BevelOuter = bvNone
      Caption = 'Copy'
      Color = 2763826
      Font.Charset = DEFAULT_CHARSET
      Font.Color = 14803686
      Font.Height = -13
      Font.Name = 'Segoe UI'
      Font.Style = []
      ParentBackground = False
      ParentFont = False
      TabOrder = 0
      OnClick = btn_CopyCmdClick
    end
  end
  object tmr_Spinner: TTimer
    Enabled = False
    Interval = 120
    OnTimer = tmr_SpinnerTimer
    Left = 340
    Top = 8
  end
end
